### ISSUE TITLE
Conflicts between question and KB facts.

### ISSUE THREAD

**Issue by RamonYeung** [yuyuz/MetaQA#2]
## Line 732 @ MetaQA/1-hop/vanilla/qa_dev.txt

Question 1:
what does [Harry Dean Stanton] star in	

Answers: 
Alien|**Paris|Texas**|Repo Man|Down Periscope|The Rose|Straight Time|Sonny|The Open Road|Man Trouble|One Magic Christmas|The Good Life|Twister|Fool for Love|Cockfighter

Corresponding facts:
**Paris, Texas**|starred_actors|Harry Dean Stanton
**Paris, Texas**|has_tags|harry dean stanton

## Line 8795 @ MetaQA/1-hop/vanilla/qa_dev.txt
Question 2:
what movies can be described by [elizabeth taylor]	

Answers:
Who's Afraid of Virginia Woolf?|Cat on a Hot Tin Roof|Giant|Cleopatra|A Place in the Sun|**Suddenly|Last Summer**|National Velvet|Reflections in a Golden Eye

Corresponding facts:
**Suddenly, Last Summer**|starred_actors|Elizabeth Taylor
**Suddenly, Last Summer**|has_tags|elizabeth taylor

**Comment by RamonYeung** [comment]
Similar situations for the following entities in 1-hop/vanilla/qa_train.txt, 1-hop/vanilla/qa_test.txt

- Suddenly, Last Summer
- Paris, Texas
- Happy, Texas
- Happy, Happy
- New York, New York
- Niagara, Niagara

And I also found entities like 'Happy' or 'Suddenly' or 'Last Summer' in kb_entity_dict.txt.

> Is this a bug, or a feature?

I personally consider this situation as a small bug and manually fix by modifying the source file I downloaded.

Thanks.

**Comment by yuyuz** [comment]
Thanks for pointing out these conflicts! Actually this should be considered as a bug from the original WikiMovies dataset (https://research.fb.com/downloads/babi/), since the delimiter is comma there and some entities do have comma in the text, which leads to confusion. The number of such cases is small, so we just ignored them. It's great if you manually fix them, but I think they have minor impact in terms of experimental performance.

**Comment by RamonYeung** [comment]
Thanks for the helpful information. I should not modify it manually since it is a released benchmark. 

I will leave this issue open for others' information. Feel free to close.
